#!/bin/bash
set -euo pipefail

devel="$(dirname "$0")"

main() {
    local version="${1:?version is required}"
    local commit
    shift
    local -a assets=("$@")

    if [[ ${#assets[@]} -eq 0 ]]; then
        echo "ERROR: no assets provided" >&2
        exit 1
    fi

    # Asserts that $version is an actual tag, not a branch name or other ref.
    git rev-parse --verify "$version^{tag}" >/dev/null

    # Translate from tag into commit for `gh release create --target`.
    commit="$(git rev-parse --verify "$version^{commit}")"

    gh release create \
        "$version" \
        --repo "${GITHUB_REPOSITORY:-nextstrain/cli}" \
        --title "$version" \
        --target "$commit" \
        --notes-file <(preamble; "$devel"/changes "$version") \
        "${assets[@]}"
}

preamble() {
    cat <<~~

_These release notes are automatically extracted from the full [changelog][]._

[changelog]: https://github.com/nextstrain/cli/blob/master/CHANGES.md#readme

~~
}

main "$@"
